/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TinyServer */

#ifndef _Included_TinyServer
#define _Included_TinyServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TinyServer
 * Method:    Init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_TinyServer_Init
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     TinyServer
 * Method:    SetSSl
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TinyServer_SetSSl
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     TinyServer
 * Method:    Start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_TinyServer_Start
  (JNIEnv *, jobject);

/*
 * Class:     TinyServer
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TinyServer_Close
  (JNIEnv *, jobject);

/*
 * Class:     TinyServer
 * Method:    Loop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_TinyServer_Loop
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
